version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    # command: "/sbin/init"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
    depends_on:
      - db
    volumes:
      - ./src:/var/www/app
    tty: true
    ports: # host:guest
      - "8000:8000"
    # privileged: true

  db:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/data:/var/lib/mysql
